MET-8: http runtime name clash
metatypedev/metatype pull request #148
Opened 2023-02-23 15:44 UTC by afmika

2023-02-23 22:47 UTC, zifeo submitted a review, later dismissed

2023-02-24 16:46 UTC, msga-mmm approved these changes
It looks good to me.

2023-02-24 18:49 UTC, Natoandro requested changes
See https://metatypedev.slack.com/archives/C03J804A7TQ/p1677264476707969

2023-03-01 18:05 UTC, Natoandro submitted a review, later dismissed

2023-03-01 18:05 UTC, Natoandro commented on typegraph/typegraph/runtimes/http.py
> +    rename_fields: Optional[Tuple[Tuple]] = field(kw_only=True, default=None)
`Optional[Tuple[Tuple[str, str]]]`?

2023-03-01 18:17 UTC, Natoandro commented on typegraph/typegraph/runtimes/http.py
> +    rename_fields: Optional[Tuple[Tuple]] = field(kw_only=True, default=None)
I think a `dict` would be easier to write; and will not produce this kind of mistake: `(("field", "renamed"))`.
You can set `field(converter=frozendict)` to automatically transform it into `frozendict`.

2023-03-02 08:43 UTC, afmika commented on typegraph/typegraph/runtimes/http.py
> +    rename_fields: Optional[Tuple[Tuple]] = field(kw_only=True, default=None)
You are right, I had errors with a raw dict as it is not hashable so I used tuple as a proof of concept. Thanks, I will try that.

2023-03-04 11:55 UTC, merged