Met-101: (copy) fix google service discovery in the tutorial
metatypedev/metatype pull request #226
Opened 2023-03-23 14:16 UTC by afmika

Copy of #225

2023-03-27 09:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/metatypedev/metatype?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/metatypedev/metatype?pullRequest=226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/metatypedev/metatype?pullRequest=226) it.</sub>

2023-03-30 07:44 UTC, Natoandro commented
See:
- Example with the OpenAPI importer: https://github.com/metatypedev/metatype/blob/94f3c6d42327622da53dc1c2b4ff1e8474609864/examples/typegraphs/petstore_v3/petstore_v3.py
- Shared code for all the importers, it will make them behave the same way: https://github.com/metatypedev/metatype/blob/94f3c6d42327622da53dc1c2b4ff1e8474609864/typegraph/typegraph/importers/base/importer.py
- https://github.com/metatypedev/metatype/blob/94f3c6d42327622da53dc1c2b4ff1e8474609864/typegraph/typegraph/importers/openapi.py

2023-03-30 21:09 UTC, zifeo commented
@afmika also, can you 1 snapshot test in python (see the other importers)?

2023-03-31 06:15 UTC, Natoandro requested changes

2023-03-31 06:15 UTC, Natoandro commented on typegraph/typegraph/importers/google_discovery_new.py
> +            self.exposed[func_key] = t.func(inp, out, Typify(lambda i, o: func_def))
Did you mean `TypifyMat`?

2023-04-01 20:49 UTC, zifeo submitted a review, later dismissed

2023-04-03 21:09 UTC, merged