docs: introduce typegraph_std
metatypedev/metatype pull request #316
Opened 2023-05-22 15:31 UTC by afmika

This solves MET-169

2023-05-22 22:31 UTC, zifeo requested changes
Feel free to also update the fcm example above - it is likely better for the user to have a dedicated how-to guide on using the importer and have the tutorial directly using it (when learning, we have to keep it simple).

2023-05-22 22:31 UTC, zifeo commented on website/docs/tutorials/import-your-existing-apis/index.mdx
> +# Introduction to typegraph_std
Can you make it a second level title with `##`? html good practice advise for a single top-level title

2023-05-22 22:31 UTC, zifeo commented on website/docs/tutorials/import-your-existing-apis/index.mdx
> +They work pretty much the same way as Importers.
little **I**mp?

2023-05-22 22:31 UTC, zifeo commented on website/docs/tutorials/import-your-existing-apis/typegraph_std.py
> +    github = import_ghes({"protocol": "https", "hostname": "custom_host"})
can we have a default setup for import_ghes? can we also use import_github so it is maybe clearer to someone not familiar with the package?

2023-05-23 05:08 UTC, Natoandro commented on website/docs/tutorials/import-your-existing-apis/index.mdx
> +- Google API (fcm, firebase, youtube, etc.)
APIs ?

2023-05-23 05:08 UTC, Natoandro commented on website/docs/tutorials/import-your-existing-apis/typegraph_std.py
> +from typegraph_std.google.gmail import import_gmail
I suggest to enable simpler imports: `from typegraph_std.google import import_gmail`

2023-05-23 21:52 UTC, zifeo approved these changes

2023-05-23 21:53 UTC, merged