feat(sdk): add wasmedge runtime
metatypedev/metatype pull request #397
Opened 2023-08-21 13:54 UTC by afmika

2023-08-21 14:44 UTC, zifeo requested changes
Sweet!

2023-08-21 14:44 UTC, zifeo commented on libs/common/src/archive.rs
> +    let bytes = fs::read(file).context(format!("reading file {:?}", file.display()))?;
with_context to lazily build the message?

2023-08-22 09:06 UTC, zifeo commented
lgtm, I let @Natoandro approve it

2023-08-24 17:07 UTC, Natoandro approved these changes
LGTM

2023-08-24 19:29 UTC, merged