fix(cli): fix for meta-cli exit with code 0 on failure
metatypedev/metatype pull request #600
Opened 2024-02-26 17:43 UTC by destifo

fix the issue where `meta-cli deploy` command exits with code 0 on failure.

#### Motivation and context

bug fix

#### Migration notes

No changes needed.

### Checklist

- [x] The change come with new or modified tests
- [ ] Hard-to-understand functions have explanatory comments
- [ ] End-user documentation is updated to reflect the change

2024-02-26 18:32 UTC, Natoandro requested changes

2024-02-26 18:32 UTC, Natoandro commented on meta-cli/src/deploy/actors/push_manager.rs
> +        _msg.failure_tx.send(self.failed_push_exists).unwrap();
You could remove the leading undescores...

2024-02-27 19:56 UTC, Yohe-Am approved these changes

2024-02-27 19:57 UTC, Yohe-Am approved these changes

2024-02-27 20:33 UTC, Natoandro approved these changes

2024-02-27 20:42 UTC, afmika approved these changes

2024-02-27 20:50 UTC, merged