fix: cache deno imports on deploy
metatypedev/metatype pull request #925
Opened 2024-11-26 11:30 UTC by luckasRanarison

- Fixes [MET-766](https://linear.app/metatypedev/issue/MET-766/typescript-import-caching-and-validation-on-deploy) and [MET-746](https://linear.app/metatypedev/issue/MET-746/deno-runtime-timeouts-on-error)

#### Migration notes

---

- [ ] The change comes with new or modified tests
- [ ] Hard-to-understand functions have explanatory comments
- [ ] End-user documentation is updated to reflect the change

2024-11-26 21:01 UTC, Natoandro submitted a review, later dismissed

2024-11-27 05:40 UTC, Natoandro submitted a review, later dismissed

2024-11-28 05:51 UTC, Yohe-Am requested changes

2024-11-28 05:51 UTC, Yohe-Am commented on src/typegate/src/runtimes/deno/hooks.ts
> +        await import(entryModulePath);
This ought to be done in a worker since some of those modules will have sideffects.

2024-11-28 16:33 UTC, michael-0acf4 commented
I just realized that Substantial also need this.

2024-12-01 16:48 UTC, Yohe-Am approved these changes

2024-12-01 18:04 UTC, Natoandro approved these changes

2024-12-02 09:58 UTC, merged