feat: python code validation
metatypedev/metatype pull request #939
Opened 2024-12-13 09:26 UTC by j03-dev

-

-

#### Migration notes

---

- [ ] The change comes with new or modified tests
- [ ] Hard-to-understand functions have explanatory comments
- [ ] End-user documentation is updated to reflect the change

2024-12-13 09:57 UTC, Natoandro requested changes

2024-12-13 09:57 UTC, Natoandro commented on src/typegate/src/runtimes/python/hooks/mod.ts
> +        Meta.py_validation.validate(entryModulePath);
Do not forget to validate the deps ;)

2024-12-16 03:14 UTC, Natoandro commented
@j03-dev Can you update the first comment, adding the details of this PR?

2024-12-19 03:05 UTC, Yohe-Am approved these changes

2024-12-24 08:28 UTC, Natoandro submitted a review, later dismissed

2024-12-27 09:45 UTC, Natoandro approved these changes

2024-12-27 09:47 UTC, merged